### ISSUE TITLE
✨ 회원 가입

### ISSUE THREAD

**Issue by JeongSangByuk** [depromeet/bbo-gak-server#71]
## 📌 Description
- 피그마 보고 회원가입 api 신규 개발

**Comment by JeongSangByuk** [comment]
🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏

**Comment by lee-june-young** [comment]
깜빡하고 브랜치 안 나누고, #2 브랜치에서 회원가입(=직군선택) api 구현해버렸네요.. 죄송함당
